### ISSUE TITLE
run srgan on my own photo

### ISSUE THREAD

**Issue by ABDOELSHEMY** [kozistr/Awesome-GANs#11]
hi @kozistr thank you for your hard and great work
could you please explain to me how to use your srgan to upscale my own photo
thank you

**Comment by kozistr** [comment]
Firstly, thanks for your interest!

Currently, using a custom dataset is kinda complicated. It means **extra codes** are needed :(
Anyway, Here's the way!

1. Loading your image that has 96x96x3 size (if the image is smaller or larger than 96x96. then it needs to be re-sized to 96x96x3! (because currently, my model is only for 96x96x3 image)
2. Training SRGAN code with any proper DataSets or Using my pre-trained model uploaded at my google drive (you can find at ```SRGAN/model/model.txt```)
3. Scaling your image data to [-1, 1] (by ```sample_x_lr=(your_image_data/127.5)-1.```)
4. Then, get your result by using below code *srgan_train.py#L178~193*
```
                    samples = s.run(model.g,
                                    feed_dict={
                                        model.x_lr: sample_x_lr,
                                        model.lr: learning_rate,
                                    })

                    # Export image generated by model G
                    sample_dir = results['output'] + 'train_{:08d}.png'.format(global_step)

                    # Generated image save
                    iu.save_images(samples,
                                   size=[1, 1],
                                   image_path=sample_dir,
                                   inv_type='127'
```

But, the Most important thing is **my SRGAN performace is verrrrrrry poor :(**.
I'm sorry, but you'd better use another SRGAN codes if you want a good result.

I'll re-make SRGAN code someday for ease of use!

If there're any questions, please feel free to leave a comment below :)
thank you

**Comment by ABDOELSHEMY** [comment]
@kozistr 
thank you very much for your quick answer and excellent Clarification, I really appreciate it 
thank you
